name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Create dist directory
      - name: Create dist folder
        run: mkdir -p dist

      # Generate snake animation
      - uses: Platane/snk@v3
        with:
          github_user_name: VMalberti
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publish to output branch
      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Generate snake animation"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
